server:
  port: 10206
spring:
  application:
    name: heifeng-cart-service
  redis:
    host: 192.168.164.131
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
heifeng:
  jwt:
    pubKeyPath: C:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: hfeng _TOKEN # cookie的名称